version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building Docker container
          no_output_timeout: 1h
          command: |
              #export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
              #docker login -u $DOCKER_USER -p $DOCKER_PASS
              #docker save $DOCKER_NAME -o /tmp/docker_image.tar
              
              docker build -t my_docker:0.1 .
              docker save my_docker:0.1 -o /tmp/my_docker.tar
      - persist_to_workspace:
          root: /tmp
          paths:
            - my_docker.tar         
      
  test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker            
      - attach_workspace:
          at: /tmp
      #- run:
      #    name: Install dependencies 
      #    command: |
      #      apk add --update make wget
      - run: 
          name: Load docker image
          no_output_timeout: 1h
          command: |
            docker load -i /tmp/my.tar
            docker images
            
workflows:
  version: 2
  my_workflow:
    jobs:
      - build
      - test
          requires:
            - build
